version: '3'
services:
  frontend:
    container_name: code-editor
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports: 
      - 3000:3000
    environment: 
      - CHOKIDAR_USEPOLLING=true